name: CI

on:
  push:
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/code_quality_check.yml

  test:
    uses: ./.github/workflows/test.yml

  publish:
    if: github.ref == 'refs/heads/main'
    needs: [check, test]
    uses: ./.github/workflows/publish.yml
